name: Linters

on: [push, pull_request]

jobs:
  rubocop:
    name: Rubocop
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.0.3

      - name: Install dependencies
        run: |
          gem install bundler
          bundle install --jobs 4 --retry 3

      - name: Run Rubocop
        run: bundle exec rubocop

  # eslint:
  #   name: ESLint
  #   runs-on: ubuntu-latest

  #   steps:
  #     - name: Checkout code
  #       uses: actions/checkout@v2

  #     - name: Install dependencies
  #       run: npm install

  #     - name: Run ESLint
        # run: npm run lint


  # tests:
    # name: Tests
    # runs-on: ubuntu-latest
    # services:
    #   postgres:
    #     image: postgres:12.7
    #     env:
    #       POSTGRES_USER: myapp
    #       POSTGRES_DB: myapp_test
    #       POSTGRES_PASSWORD: ""
    #     ports: ["5432:5432"]

    # steps:
    #   - name: Checkout code
    #     uses: actions/checkout@v2

    #   - name: Setup Ruby and install gems
    #     uses: ruby/setup-ruby@v1
    #     with:
    #       bundler-cache: true

    #   - name: Setup Node
    #     uses: actions/setup-node@v2
    #     with:
    #       node-version: 16
    #       cache: yarn

    #   - name: Install packages
    #     run: |
    #       yarn install --pure-lockfile

    #   - name: Setup test database
    #     env:
    #       RAILS_ENV: test
    #       PGHOST: localhost
    #       PGUSER: myapp
    #     run: |
    #       bin/rails db:setup

    #   - name: Run tests
    #     run: bin/rspec